name: Create releae on TOC Bump

on:
  push:
    paths:
      - '**toc-bump.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get next version
        uses: reecetech/version-increment@2023.10.1
        id: version
        with:
          scheme: semver
          increment: patch
          use_api: true

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.version.outputs.v-version }}',
              sha: context.sha
            })