name: Create releae on TOC Bump

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit message'
        required: false
        default: 'TOC Bump'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Release snapshot
        id: release-snapshot
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.v-version }}
          release_name: ${{ steps.version.outputs.v-version }}
          draft: false
          prerelease: false
