name: Create releae on TOC Bump

on:
  push:
    paths:
      - '**toc-bump.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get next version
        uses: reecetech/version-increment@2023.10.1
        id: version
        with:
          scheme: semver
          increment: patch
          use_api: true

      - name: Create git tag
        run: |
          git tag ${{ steps.version.outputs.v-version }}

      - name: Push git tag
        run: git push origin ${{ steps.version.outputs.v-version }}